### ISSUE TITLE
Hello Hakeem

### ISSUE THREAD

**Issue by KimJinsu66** [hakeem-kim/ChungHaeJin_Class#1]
Hello Hakeem
My name is Jinsu Kim
I'm your friend!
Good night cool guy!

**Comment by hakeem-kim** [comment]
笑笑 かわいい私の友達😊😊

2020년 11월 17일 (화) 01:18, JINSU KIM <notifications@github.com>님이 작성:

**Comment by KimJinsu66** [comment]
おはようございます！
頑張ってください！

**Comment by hakeem-kim** [comment]
頑張ります！

2020년 11월 17일 (화) 오전 10:55, JINSU KIM <notifications@github.com>님이 작성:
